apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forestrie-arbor
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: scout
  component: api
images:
  - name: europe-west2-docker.pkg.dev/forest-dev-1/forestrie/scout
    newTag: main-bacdd81-294 # {"$imagepolicy": "flux-system:scout:tag"}
configMapGenerator:
  - name: scout-config
    literals:
      - log-level=info
      - shutdown-timeout=30s
