package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ShardAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ShardAssignmentSpec   `json:"spec,omitempty"`
	Status            ShardAssignmentStatus `json:"status,omitempty"`
}

type ShardAssignmentSpec struct {
	OwnerSelector *metav1.LabelSelector `json:"ownerSelector,omitempty"`
	HolderName    string                `json:"holderName,omitempty"`
	HolderUID     string                `json:"holderUID,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardAssignmentSpec) DeepCopyInto(out *ShardAssignmentSpec) {
	*out = *in
	if in.OwnerSelector != nil {
		in, out := &in.OwnerSelector, &out.OwnerSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

type ShardAssignmentStatus struct {
	Phase string `json:"phase,omitempty"` // "Unassigned" | "Held"
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardAssignmentStatus) DeepCopyInto(out *ShardAssignmentStatus) {
	*out = *in
}

// +kubebuilder:object:root=true
type ShardAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ShardAssignment `json:"items"`
}
